before_script:
  - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"

stages:
  - build

Build and publish Docker image:
  stage: build
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}/rtsp_bruter:latest  .
    - docker push ${CI_REGISTRY_IMAGE}/rtsp_bruter:latest

